---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - infrastructure.example.com
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.example.com
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.example.com
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
